<a href="https://colab.research.google.com/github/A01737838/Modelos-de-Regresi-n-Lineal/blob/main/Modelos%20de%20Regresi%C3%B3n%20Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [ ]:
df= pd.read_csv("cuentas_credicel.csv", encoding= 'latin')
pd.options.display.max_columns = None
df.head(2)

In [ ]:
df.info()

**Convertir columna plazo**

In [ ]:
#Eliminar un signo de una columna
df['plazo']=df['plazo'].str.replace('S', '')

In [ ]:
#Conversión de tipo de dato de columna de tipo Object a int
df['plazo']= df['plazo'].astype(int)

**Convertir riesgo**

In [ ]:
#Sustituyo los strings Atraso, Cancelado y Fraude por la constante "0"
df['riesgo']=df['riesgo'].str.replace('Atraso', '0')
df['riesgo']=df['riesgo'].str.replace('Cancelado', '0')
df['riesgo']=df['riesgo'].str.replace('Fraude', '0')

In [ ]:
riesgo_categorias = df.groupby(['riesgo'])['riesgo'].count()
riesgo_categorias

In [ ]:
df["riesgo"]= df["riesgo"].fillna(0)

In [ ]:
df["porc_enganche"]=df["porc_enganche"].fillna(method="bfill")

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

**1er Modelo Matemático: y=8.30362837x+928.5596445591957**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.08237539697677103

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['precio']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

**2do Modelo Matemático: y= -7.11615993x +3995.217831233963**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([3995.21783123, 3995.21783123, 3995.21783123, ..., 3995.21783123,
       3995.21783123, 3995.21783123])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0006109088972575671

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.02471657130869019

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['costo_total']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-18.95458459]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 5694.847880533092}

**3er Modelo Matemático: y=-18.95458459x+5694.84788053309**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([5694.84788053, 5694.84788053, 5694.84788053, ..., 5694.84788053,
       5694.84788053, 5694.84788053])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.001411319050099502

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.03756752653688425

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['pagos_realizados']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-0.03282908]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 10.172388024218485}

**4to Modelo Matemático: y=-0.03282908x +10.172388024218485**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([10.17238802, 10.17238802, 10.17238802, ..., 10.17238802,
       10.17238802, 10.17238802])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0002557069223527719

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.015990838700730238

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['riesgo']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.02461996]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 2.1603808207395727}

**5to Modelo Matemático: y=0.02461996x+2.1603808207395727**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([2.16038082, 2.16038082, 2.16038082, ..., 2.16038082, 2.16038082,
       2.16038082])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

7.007499711020326e-05

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.00837108100009809

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['plazo']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.06482148]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 25.926221898296898}

**6to Modelo Matemático: y=0.06482148x+25.926221898296898**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([25.9262219, 25.9262219, 25.9262219, ..., 25.9262219, 25.9262219,
       25.9262219])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0009418250456870725

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.030689168214323968

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['monto_financiado']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-15.3639206]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 3072.209876915044}

**7mo Modelo Matemático: y=-15.3639206x +3072.209876915044**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([3072.20987692, 3072.20987692, 3072.20987692, ..., 3072.20987692,
       3072.20987692, 3072.20987692])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.00438865960173207

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['porc_enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-0.07220764]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 0.8455734321126249}

**8vo Modelo Matemático: y=-0.07220764x + 0.8455734321126249**

In [ ]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([0.84557343, 0.84557343, 0.84557343, ..., 0.84557343, 0.84557343,
       0.84557343])

In [ ]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.002932300047172931

In [ ]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.0541507160356438